In [1]:
import torch

***torch.take(input, index) → Tensor***  
Returns a new tensor with the elements of input at the given indices. The input tensor is treated as if it were viewed as a 1-D tensor. The result takes the same shape as the indices.


In [2]:
src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

***torch.tile(input, dims) → Tensor***  
Constructs a tensor by repeating the elements of input. The dims argument specifies the number of repetitions in each dimension.

- If dims specifies fewer dimensions than input has, then ones are prepended to dims until all dimensions are specified. For example, if input has shape (8, 6, 4, 2) and dims is (2, 2), then dims is treated as (1, 1, 2, 2).

- Analogously, if input has fewer dimensions than dims specifies, then input is treated as if it were unsqueezed at dimension zero until it has as many dimensions as dims specifies. For example, if input has shape (4, 2) and dims is (3, 3, 2, 2), then input is treated as if it had the shape (1, 1, 4, 2).

In [3]:
x = torch.tensor([1, 2, 3])
print(x.tile((2,))) #逗号可不用
y = torch.tensor([[1, 2], [3, 4]])
print(torch.tile(y, (2,))) #逗号必须有，当需要ints但只想输入int,自带填充为（1,2）
torch.tile(y, (2, 2))

tensor([1, 2, 3, 1, 2, 3])
tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])


tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [4]:
a = torch.rand(4,3)
a_tile = torch.tile(a, [2,1])  # 行复制两份，列不变
print(a_tile)
a_tile = torch.tile(a, [1,3]) # 列复制三次
a_tile

tensor([[0.9228, 0.0161, 0.6526],
        [0.7565, 0.5744, 0.6347],
        [0.1929, 0.1008, 0.2746],
        [0.9741, 0.1085, 0.5771],
        [0.9228, 0.0161, 0.6526],
        [0.7565, 0.5744, 0.6347],
        [0.1929, 0.1008, 0.2746],
        [0.9741, 0.1085, 0.5771]])


tensor([[0.9228, 0.0161, 0.6526, 0.9228, 0.0161, 0.6526, 0.9228, 0.0161, 0.6526],
        [0.7565, 0.5744, 0.6347, 0.7565, 0.5744, 0.6347, 0.7565, 0.5744, 0.6347],
        [0.1929, 0.1008, 0.2746, 0.1929, 0.1008, 0.2746, 0.1929, 0.1008, 0.2746],
        [0.9741, 0.1085, 0.5771, 0.9741, 0.1085, 0.5771, 0.9741, 0.1085, 0.5771]])

***torch.transpose(input, dim0, dim1) → Tensor***  
Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.  
The resulting out tensor shares its underlying storage with the input tensor, so changing the content of one would change the content of the other.

In [5]:
print(a.shape)
b = torch.transpose(a, 1, 0)  # 1,0顺序对结果无影响
b, b.shape

torch.Size([4, 3])


(tensor([[0.9228, 0.7565, 0.1929, 0.9741],
         [0.0161, 0.5744, 0.1008, 0.1085],
         [0.6526, 0.6347, 0.2746, 0.5771]]),
 torch.Size([3, 4]))

***torch.unbind(input, dim=0) → seq***  
Removes a tensor dimension.  
Returns a tuple of all slices along a given dimension, already without it.

In [6]:
torch.unbind(torch.tensor([[1, 2, 3],  #默认按dim=0拆开
                           [4, 5, 6],
                           [7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [7]:
torch.unbind(a, dim=0) 

(tensor([0.9228, 0.0161, 0.6526]),
 tensor([0.7565, 0.5744, 0.6347]),
 tensor([0.1929, 0.1008, 0.2746]),
 tensor([0.9741, 0.1085, 0.5771]))

In [8]:
torch.unbind(a, dim=1) #按列拆开

(tensor([0.9228, 0.7565, 0.1929, 0.9741]),
 tensor([0.0161, 0.5744, 0.1008, 0.1085]),
 tensor([0.6526, 0.6347, 0.2746, 0.5771]))

In [9]:
a = torch.rand(2,3,4)
a

tensor([[[0.6670, 0.5995, 0.1082, 0.4240],
         [0.6096, 0.5035, 0.2299, 0.7610],
         [0.7912, 0.1218, 0.7202, 0.6910]],

        [[0.2482, 0.7953, 0.9644, 0.7697],
         [0.7763, 0.5768, 0.3460, 0.5184],
         [0.3196, 0.4814, 0.5056, 0.4427]]])

In [10]:
torch.unbind(a)

(tensor([[0.6670, 0.5995, 0.1082, 0.4240],
         [0.6096, 0.5035, 0.2299, 0.7610],
         [0.7912, 0.1218, 0.7202, 0.6910]]),
 tensor([[0.2482, 0.7953, 0.9644, 0.7697],
         [0.7763, 0.5768, 0.3460, 0.5184],
         [0.3196, 0.4814, 0.5056, 0.4427]]))

In [11]:
torch.unbind(a, dim=1),torch.unbind(a, dim=2)

((tensor([[0.6670, 0.5995, 0.1082, 0.4240],
          [0.2482, 0.7953, 0.9644, 0.7697]]),
  tensor([[0.6096, 0.5035, 0.2299, 0.7610],
          [0.7763, 0.5768, 0.3460, 0.5184]]),
  tensor([[0.7912, 0.1218, 0.7202, 0.6910],
          [0.3196, 0.4814, 0.5056, 0.4427]])),
 (tensor([[0.6670, 0.6096, 0.7912],
          [0.2482, 0.7763, 0.3196]]),
  tensor([[0.5995, 0.5035, 0.1218],
          [0.7953, 0.5768, 0.4814]]),
  tensor([[0.1082, 0.2299, 0.7202],
          [0.9644, 0.3460, 0.5056]]),
  tensor([[0.4240, 0.7610, 0.6910],
          [0.7697, 0.5184, 0.4427]])))

***torch.unsqueeze(input, dim) → Tensor***  
Returns a new tensor with a dimension of size one inserted at the specified position.  
The returned tensor shares the same underlying data with this tensor.  
- A dim value within the range [-input.dim() - 1, input.dim() + 1) can be used. Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1.

In [12]:
x = torch.tensor([1, 2, 3, 4]) # shape=4
print(torch.unsqueeze(x, 0))   # shape=(1,4)
torch.unsqueeze(x, 1)          # shape=(4,1)

tensor([[1, 2, 3, 4]])


tensor([[1],
        [2],
        [3],
        [4]])

In [13]:
a.shape

torch.Size([2, 3, 4])

In [14]:
torch.unsqueeze(a, dim=0).shape

torch.Size([1, 2, 3, 4])

In [15]:
torch.unsqueeze(a, dim=1).shape

torch.Size([2, 1, 3, 4])

In [16]:
torch.unsqueeze(a, dim=-1).shape

torch.Size([2, 3, 4, 1])

***torch.where(condition, x, y) → Tensor***  
Return a tensor of elements selected from either x or y, depending on condition.  
The operation is defined as:  
$$\text{out}_i = \begin{cases} \text{x}_i & \text{if } \text{condition}_i \\ \text{y}_i & \text{otherwise} \\ \end{cases}$$
- The tensors condition, x, y must be broadcastable.
- Currently valid scalar and tensor combination are 1. Scalar of floating dtype and torch.double 2. Scalar of integral dtype and torch.long 3. Scalar of complex dtype and torch.complex128



In [17]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
print(x)
torch.where(x > 0, x, y)  #小于0的数用1填充


tensor([[-0.8494,  0.8418],
        [-0.8854,  0.9635],
        [-1.0736,  0.0103]])


tensor([[1.0000, 0.8418],
        [1.0000, 0.9635],
        [1.0000, 0.0103]])

In [18]:
x = torch.randn(2, 2, dtype=torch.double)
print(x)
torch.where(x > 0, x, 0.)

tensor([[-0.5519,  1.4211],
        [-1.5213, -0.2387]], dtype=torch.float64)


tensor([[0.0000, 1.4211],
        [0.0000, 0.0000]], dtype=torch.float64)

In [19]:
a = torch.rand(2,2)
a

tensor([[0.8896, 0.9667],
        [0.1533, 0.3792]])

In [20]:
b = torch.zeros_like(a)
b

tensor([[0., 0.],
        [0., 0.]])

In [21]:
torch.where(a>0.5, a, b)

tensor([[0.8896, 0.9667],
        [0.0000, 0.0000]])

In [22]:
torch.where(a>0.5, a, torch.tensor(0,dtype=torch.float)) # 直接用0.为float64,而输入要为float32，要转换一下类型

tensor([[0.8896, 0.9667],
        [0.0000, 0.0000]])

***torch.manual_seed(seed)***  
Sets the seed for generating random numbers. Returns a torch.Generator object.    
- Parameters ：**seed (int)** – The desired seed. Value must be within the inclusive range [-0x8000_0000_0000_0000, 0xffff_ffff_ffff_ffff]. Otherwise, a RuntimeError is raised. Negative inputs are remapped to positive values with the formula 0xffff_ffff_ffff_ffff + seed.  
为生成随机数设置一个种子，只要种子固定，每次运行随机数是相同的

***torch.bernoulli(input, *, generator=None, out=None) → Tensor***  
Draws binary random numbers (0 or 1) from a Bernoulli distribution.  

The input tensor should be a tensor containing probabilities to be used for drawing the binary random number. Hence, all values in input have to be in the range: $$0 \leq \text{input}_i \leq 1$$


The $\text{i}^{th}$element of the output tensor will draw a value 1 according to the $\text{i}^{th}$probability value given in input.

$$\text{out}_{i} \sim \mathrm{Bernoulli}(p = \text{input}_{i})$$

- The returned out tensor only has values 0 or 1 and is of the same shape as input.

- out can have integral dtype, but input must have floating point dtype.

In [23]:
a = torch.empty(3, 3).uniform_(0, 1)  # generate a uniform randomc
a

tensor([[0.4438, 0.6802, 0.7170],
        [0.4582, 0.3329, 0.1412],
        [0.9482, 0.5840, 0.8048]])

In [24]:
 torch.bernoulli(a) # 按照相应概率生成1

tensor([[0., 1., 0.],
        [0., 0., 0.],
        [1., 0., 1.]])

In [25]:
a = torch.ones(3, 3) # probability of drawing "1" is 1
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
a = torch.zeros(3, 3) # probability of drawing "1" is 1
torch.bernoulli(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

***torch.normal(mean, std, *, generator=None, out=None) → Tensor***  
Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.  
- The **mean** is a tensor with the mean of each output element’s normal distribution
- The **std** is a tensor with the standard deviation of each output element’s normal distribution
- The shapes of **mean** and **std** don’t need to match, but the total number of elements in each tensor need to be the same.  
生成正态分布（高斯分布）的数据

In [27]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1)) # mean和std长度相符，生成每个值由相应mean和std采样得到

tensor([ 2.9494,  1.5823,  3.6664,  4.2745,  4.4848,  6.6257,  6.4806,  7.8453,
         8.9944, 10.0682])

In [28]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))  # 均值相同，按不同的标准差生成5个数，也可共享std，不同mean

tensor([ 0.4567,  2.3679,  4.9064, -6.6401, -2.7932])

In [29]:
torch.normal(2, 3, size=(1, 4)) #四个元素均为mean为2，std为3

tensor([[4.3416, 0.6485, 2.8688, 3.2339]])

***torch.rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor***
- Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)  
- The shape of the tensor is defined by the variable argument size.

In [30]:
torch.rand(2, 3)   # rand从[0,1)中均匀抽取浮点数

tensor([[0.8935, 0.2138, 0.9452],
        [0.1513, 0.7215, 0.8698]])

In [31]:
print(torch.randint(3, 5, (3,)))  #前两个数字为下上界，若仅一个数则为上界，仅返回整形
torch.randint(10, (2, 2))

tensor([4, 3, 4])


tensor([[3, 4],
        [5, 1]])

In [32]:
torch.randn(2, 3)  # randn为均值为0，标准差为1的正态分布

tensor([[-0.1902, -0.6669,  0.2939],
        [-0.3962,  1.3867, -0.2899]])

In [33]:
torch.randperm(4) #0到n-1随机组合，可用于生成随机索引

tensor([1, 3, 2, 0])