In [1]:
import torch

In [2]:
#----------------------------张量的一些常见操作------------------------------

In [3]:
#torch.trunk可以将一个张量在dim维度（默认为0）上分割成多个张量
b = torch.rand([3,2])
b

tensor([[0.5157, 0.5043],
        [0.1654, 0.0428],
        [0.3105, 0.0638]])

In [4]:
c,d = torch.chunk(b, chunks=2)
c,d

(tensor([[0.5157, 0.5043],
         [0.1654, 0.0428]]),
 tensor([[0.3105, 0.0638]]))

In [5]:
c,d = torch.chunk(b, chunks=2, dim=1)
c,d

(tensor([[0.5157],
         [0.1654],
         [0.3105]]),
 tensor([[0.5043],
         [0.0428],
         [0.0638]]))

In [6]:
b, torch.reshape(b,[2,3]), torch.reshape(b,[-1])

(tensor([[0.5157, 0.5043],
         [0.1654, 0.0428],
         [0.3105, 0.0638]]),
 tensor([[0.5157, 0.5043, 0.1654],
         [0.0428, 0.3105, 0.0638]]),
 tensor([0.5157, 0.5043, 0.1654, 0.0428, 0.3105, 0.0638]))

In [7]:
#torch.scatter: 根据dim和index将src张量中填充到结果张量相应位置中
#self[index[i][j][k]][j][k] = src[i][j][k]  # if dim == 0
#self[i][index[i][j][k]][k] = src[i][j][k]  # if dim == 1
#self[i][j][index[i][j][k]] = src[i][j][k]  # if dim == 2
src = torch.arange(1, 11).reshape((2, 5))
index = torch.tensor([[0, 1, 2, 0]])
src,torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[1, 0, 0, 4, 0],
         [0, 2, 0, 0, 0],
         [0, 0, 3, 0, 0]]))

In [8]:
index = torch.tensor([[0, 1, 2], [0, 1, 4]])
src,torch.zeros(3, 5, dtype=src.dtype).scatter_(1, index, src)

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[1, 2, 3, 0, 0],
         [6, 7, 0, 0, 8],
         [0, 0, 0, 0, 0]]))

In [9]:
#torch.split(tensor, split_size_or_sections, dim=0)，其和trunk不同之处是可以传入列表
a = torch.arange(10).reshape(5,2)
a,torch.split(a, 2)

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 (tensor([[0, 1],
          [2, 3]]),
  tensor([[4, 5],
          [6, 7]]),
  tensor([[8, 9]])))

In [10]:
torch.split(a, [1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

In [11]:
# torch.squeeze(input, dim=None, *, out=None) → Tensor:将input所有维度为1的维度移除
# When dim is given, a squeeze operation is done only in the given dimension. 
a = torch.rand([3,2])
a,a.shape

(tensor([[0.0269, 0.8336],
         [0.8525, 0.6724],
         [0.4594, 0.2976]]),
 torch.Size([3, 2]))

In [12]:
torch.reshape(a,[3,1,2])

tensor([[[0.0269, 0.8336]],

        [[0.8525, 0.6724]],

        [[0.4594, 0.2976]]])

In [13]:
torch.squeeze(torch.reshape(a,[3,1,2]))

tensor([[0.0269, 0.8336],
        [0.8525, 0.6724],
        [0.4594, 0.2976]])

In [14]:
b = torch.reshape(a, [3,1,2,1,1])
b

tensor([[[[[0.0269]],

          [[0.8336]]]],



        [[[[0.8525]],

          [[0.6724]]]],



        [[[[0.4594]],

          [[0.2976]]]]])

In [34]:
torch.squeeze(b,dim=1).shape   # dim不能为元组和列表

torch.Size([3, 2, 1, 1])

In [38]:
#torch.stack(tensors, dim=0, *, out=None) → Tensor
#Concatenates a sequence of tensors along a new dimension.
#All tensors need to be of the same size.
b = torch.rand([3,2])
a,b

(tensor([[0.0269, 0.8336],
         [0.8525, 0.6724],
         [0.4594, 0.2976]]),
 tensor([[0.9851, 0.9161],
         [0.0157, 0.1180],
         [0.2099, 0.2222]]))

In [42]:
torch.stack([a,b]),torch.stack([a,b]).shape

(tensor([[[0.0269, 0.8336],
          [0.8525, 0.6724],
          [0.4594, 0.2976]],
 
         [[0.9851, 0.9161],
          [0.0157, 0.1180],
          [0.2099, 0.2222]]]),
 torch.Size([2, 3, 2]))

In [45]:
torch.stack([a,b], dim=1),torch.stack([a,b], dim=1).shape

(tensor([[[0.0269, 0.8336],
          [0.9851, 0.9161]],
 
         [[0.8525, 0.6724],
          [0.0157, 0.1180]],
 
         [[0.4594, 0.2976],
          [0.2099, 0.2222]]]),
 torch.Size([3, 2, 2]))

In [46]:
torch.stack([a,b], dim=2),torch.stack([a,b], dim=1).shape

(tensor([[[0.0269, 0.9851],
          [0.8336, 0.9161]],
 
         [[0.8525, 0.0157],
          [0.6724, 0.1180]],
 
         [[0.4594, 0.2099],
          [0.2976, 0.2222]]]),
 torch.Size([3, 2, 2]))