In [69]:
import torch

In [70]:
#-----------------从列表中创建一个张量--------------------

In [71]:
a = [1,2,3.]
type(a)

list

In [72]:
b = torch.tensor(a)
b,type(b),b.dtype

(tensor([1., 2., 3.]), torch.Tensor, torch.float32)

In [73]:
#----------------从numpy数组中创建一个张量---------------------

In [74]:
import numpy as np
np.random.normal(2)

1.980114824932926

In [75]:
a = np.random.normal((2,3))
a,type(a)

(array([1.83103621, 1.77690734]), numpy.ndarray)

In [76]:
torch.tensor(a) #默认为float64 或 int64

tensor([1.8310, 1.7769], dtype=torch.float64)

In [77]:
#----------------生成与原有张量形状相同的张量---------------------

In [78]:
b = torch.tensor(a)
b

tensor([1.8310, 1.7769], dtype=torch.float64)

In [79]:
c = torch.ones_like(b) #生成一个和b形状一样的全1张量
d = torch.zeros_like(b) #生成一个和b形状一样的全0张量 
e = torch.rand_like(b) #生成一个和b形状一样的随机张量 
c,d,e

(tensor([1., 1.], dtype=torch.float64),
 tensor([0., 0.], dtype=torch.float64),
 tensor([0.0795, 0.0099], dtype=torch.float64))

In [80]:
#----------------根据形状生成张量---------------------

In [81]:
a = torch.rand((2,2))
b = torch.rand([2,2])
c = torch.rand([2,2,])    #元组，列表或者多逗号都不影响，但是字典{}不行
a,b,c,a.dtype      #torch.rand数据类型为float32

(tensor([[0.9025, 0.6986],
         [0.7578, 0.8346]]),
 tensor([[0.2079, 0.0777],
         [0.7669, 0.3325]]),
 tensor([[0.9384, 0.6517],
         [0.6239, 0.2918]]),
 torch.float32)

In [82]:
#查看张量的不同属性
a.dtype, a.shape, a.device

(torch.float32, torch.Size([2, 2]), device(type='cpu'))

In [83]:
#----------------关于张量的一系列操作（上百种，详见官网）---------------------

In [84]:
#可以将tensor移动到gpu的cuda上
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
torch.cuda.is_available()

False

In [85]:
torch.is_tensor(a)

True

In [86]:
a = torch.tensor(1.0) #单一元素
b = torch.tensor(0)
torch.is_nonzero(a),torch.is_nonzero(b)

(True, False)

In [87]:
c,torch.numel(c) #c.shape的几个数字连乘的结果，元素个数

(tensor([[0.9384, 0.6517],
         [0.6239, 0.2918]]),
 4)

In [88]:
torch.zeros(5,5), torch.zeros(5,5).dtype, torch.zeros((5,5),dtype=torch.int32)

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.float32,
 tensor([[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]], dtype=torch.int32))

In [89]:
a = torch.zeros((5,5),dtype=torch.int32)
torch.ones_like(a)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [90]:
#两个常用的API：range和arange
torch.arange(5) #默认start为0，step为1，前闭后开

tensor([0, 1, 2, 3, 4])

In [91]:
torch.arange(0,5,2)

tensor([0, 2, 4])

In [92]:
#range输出比arange长一位,且arange默认int64，range为float32（range将被弃用）
torch.range(0,5), torch.range(0,5).dtype

D:\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


(tensor([0., 1., 2., 3., 4., 5.]), torch.float32)

In [93]:
#一般情况遍历用arange即可
for i in torch.arange(10):
    print("epoch:",i)

epoch: tensor(0)
epoch: tensor(1)
epoch: tensor(2)
epoch: tensor(3)
epoch: tensor(4)
epoch: tensor(5)
epoch: tensor(6)
epoch: tensor(7)
epoch: tensor(8)
epoch: tensor(9)


In [94]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [95]:
torch.full([2,2],5)

tensor([[5, 5],
        [5, 5]])

In [96]:
#torch.cat可以在dim维度（默认为0）进行拼接
a = torch.rand([2,2])
b = torch.rand([2,3])
a,b

(tensor([[0.9081, 0.9073],
         [0.1092, 0.0842]]),
 tensor([[0.8583, 0.2868, 0.4292],
         [0.1352, 0.5834, 0.0956]]))

In [97]:
torch.cat([a,b],dim=1)

tensor([[0.9081, 0.9073, 0.8583, 0.2868, 0.4292],
        [0.1092, 0.0842, 0.1352, 0.5834, 0.0956]])

In [98]:
a = torch.rand([2,2])
b = torch.rand([3,2])
a,b

(tensor([[0.8531, 0.8412],
         [0.3155, 0.5532]]),
 tensor([[0.2499, 0.3828],
         [0.7245, 0.1661],
         [0.6446, 0.4706]]))

In [99]:
torch.cat([a,b],dim=0)

tensor([[0.8531, 0.8412],
        [0.3155, 0.5532],
        [0.2499, 0.3828],
        [0.7245, 0.1661],
        [0.6446, 0.4706]])